#!/usr/bin/env groovy

pipeline {
  agent any
  options {
    disableConcurrentBuilds()
    timeout(time: 1, unit: 'HOURS')
  }
  stages {
    stage('Checkout') {
      steps {
        echo 'Checkout'
      }
    }
    stage('Install') {
      steps {
        echo 'Install Dependencies'
        dir('./front/'){
          sh 'npm install'
        }
      }
    }
    stage('Lint') {
      steps {
        echo 'Typescript Linter'
        dir('./front/'){
          sh 'npm run lint'
        }
      }
    }
    stage('Test') {
      steps {
        echo 'Karma Test'
        dir('./front/'){
          sh 'npm run coverage'
        }
      }
    }
    stage('Sonar') {
      steps {
        echo 'Sonar Analysis'
        withSonarQubeEnv('Sonarqube_env'){
          dir('./front'){
            sh 'npm run sonar'
          }
        }
      }
    }
    stage('Quality Gate') {
      steps {
        timeout(time: 1, unit: 'HOURS') {
          waitForQualityGate true
        }
      }
    }
    stage('Deployment'){
      when {
        expression { env.GIT_BRANCH == 'master' }
      }
      steps {
        dir('/front/') {
          echo 'Deployement'
          sh 'npm run deploy'
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'front/coverage/**/*', fingerprint: true
      echo 'JENKINS PIPELINE'
    }

    success {
      slackSend(
        channel: 'otake',
        failOnError: true,
        color: 'good',
        token: env.SLACK_TOKEN,
        message: 'Job: ' + env.JOB_NAME + ' with buildnumber ' + env.BUILD_NUMBER + ' was successful',
        baseUrl: env.SLACK_WEBHOOK)

      echo 'JENKINS PIPELINE SUCCESSFUL'
    }

    failure {
      slackSend(
        channel: 'otake',
        failOnError: true,
        color: 'danger',
        token: env.SLACK_TOKEN,
        message: 'Job: ' + env.JOB_NAME + ' with buildnumber ' + env.BUILD_NUMBER + ' was failed\n ' +
        env.GIT_COMMITTER_NAME + 'has done something wrong',
        baseUrl: env.SLACK_WEBHOOK)

      echo 'JENKINS PIPELINE FAILED'
    }

    unstable {
      slackSend(
        channel: 'otake',
        failOnError: true,
        color: 'warning',
        token: env.SLACK_TOKEN,
        message: 'Job: ' + env.JOB_NAME + ' with buildnumber ' + env.BUILD_NUMBER + ' was unstable',
        baseUrl: env.SLACK_WEBHOOK)

      echo 'JENKINS PIPELINE WAS MARKED AS UNSTABLE'
    }

    changed {
      slackSend(
        channel: 'otake',
        failOnError: true,
        color: 'danger',
        token: env.SLACK_TOKEN,
        message: 'Job: ' + env.JOB_NAME + ' with buildnumber ' + env.BUILD_NUMBER + ' its resulat was unclear',
        baseUrl: env.SLACK_WEBHOOK)

      echo 'JENKINS PIPELINE STATUS HAS CHANGED SINCE LAST EXECUTION'
    }
  }
}
