const BaseModel = require('./base-model.js');

module.exports = new BaseModel('city', t => {
  t.increments('id').primary();
  t.string('name', 50).unique();
  t.integer('country_id').references('id').inTable('country');
},
[
  { id: 0, name: 'Rio de Janeiro', country_id: 1 },
  { id: 1, name: 'London', country_id: 2 },
  { id: 2, name: 'Windsor', country_id: 2 },
  { id: 3, name: 'Montréal', country_id: 2 },
  { id: 4, name: 'Sherbrooke', country_id: 2 },
  { id: 5, name: 'Saint- Jean de Terre - Neuve', country_id: 2 },
  { id: 6, name: 'Québec', country_id: 2 },
  { id: 7, name: 'Trois-Rivières', country_id: 2 },
  { id: 8, name: 'Rimouski', country_id: 2 },
  { id: 9, name: 'Abitibi-Témiscamingue', country_id: 2 },
  { id: 10, name: 'Outaouais', country_id: 2 },
  { id: 11, name: 'Toronto', country_id: 2 },
  { id: 12, name: 'Saguenay', country_id: 2 },
  { id: 13, name: 'Kaohsiung', country_id: 3 },
  { id: 14, name: 'Oklahoma city', country_id: 4 },
  { id: 15, name: 'Hong Kong', country_id: 0 },
  { id: 16, name: 'Tianjin', country_id: 0 },
  { id: 17, name: 'Tongji', country_id: 0 },
  { id: 18, name: 'Xi\'an', country_id: 0 },
  { id: 19, name: 'Incheon', country_id: 5 },
  { id: 20, name: 'Bangkok', country_id: 6 },
  { id: 21, name: 'Danang', country_id: 7 },
  { id: 22, name: 'Cottbus', country_id: 8 },
  { id: 23, name: 'Darmstadt', country_id: 8 },
  { id: 24, name: 'Brunswick', country_id: 8 },
  { id: 25, name: 'Bruxelles', country_id: 9 },
  { id: 26, name: 'Liège', country_id: 9 },
  { id: 27, name: 'Louvain', country_id: 9 },
  { id: 28, name: 'Mons', country_id: 9 },
  { id: 29, name: 'Aalborg', country_id: 10 },
  { id: 30, name: 'Copenhague', country_id: 10 },
  { id: 31, name: 'Catalogne', country_id: 11 },
  { id: 32, name: 'La Corogne ', country_id: 11 },
  { id: 33, name: 'Grenade', country_id: 11 },
  { id: 34, name: 'Las Palmas de Grande Canarie', country_id: 11 },
  { id: 35, name: 'Madrid', country_id: 11 },
  { id: 36, name: 'Séville', country_id: 11 },
  { id: 37, name: 'Budapest', country_id: 12 },
  { id: 38, name: 'Dublin', country_id: 13 },
  { id: 39, name: 'Bologne', country_id: 14 },
  { id: 40, name: 'Turin', country_id: 14 },
  { id: 41, name: 'Milan', country_id: 14 },
  { id: 42, name: 'Vérone', country_id: 14 },
  { id: 43, name: 'Aquila', country_id: 14 },
  { id: 44, name: 'Naples', country_id: 14 },
  { id: 45, name: 'Rome', country_id: 14 },
  { id: 46, name: 'Trente', country_id: 14 },
  { id: 47, name: 'Trondheim', country_id: 15 },
  { id: 48, name: 'Gdansk', country_id: 16 },
  { id: 49, name: 'Cracovie', country_id: 16 },
  { id: 50, name: 'Varsovie', country_id: 16 },
  { id: 51, name: 'Lisbonne', country_id: 17 },
  { id: 52, name: 'Porto', country_id: 17 },
  { id: 53, name: 'Sibiu', country_id: 18 },
  { id: 54, name: 'Timisoara', country_id: 18 },
  { id: 55, name: 'Bucarest', country_id: 18 },
  { id: 56, name: 'Newcastle upon Tyne', country_id: 19 },
  { id: 57, name: 'Linköping', country_id: 20 },
  { id: 58, name: 'Santa Fe', country_id: 21 },
  { id: 59, name: 'Fortaleza', country_id: 3 },
  { id: 60, name: 'Sobral', country_id: 3 },
  { id: 61, name: 'Barbalha', country_id: 3 },
  { id: 62, name: 'Vitória', country_id: 3 },
  { id: 63, name: 'Yaoundé', country_id: 22 },
  { id: 64, name: 'Bari', country_id: 14 },
  { id: 65, name: 'Rabat', country_id: 23 },
  { id: 66, name: 'Tétouan', country_id: 23 },
  { id: 67, name: 'Berne', country_id: 24 },
  { id: 68, name: 'Lomé', country_id: 25 }
]);
