const BaseModel = require('./base-model.js');

module.exports = new BaseModel('city', t => {
  t.increments('id').primary();
  t.string('city_name', 50).unique();
  t.integer('country_id').references('id').inTable('country');
},
[
  { id: 0, city_name: 'Rio de Janeiro', country_id: 1 },
  { id: 1, city_name: 'London', country_id: 2 },
  { id: 2, city_name: 'Windsor', country_id: 2 },
  { id: 3, city_name: 'Montréal', country_id: 2 },
  { id: 4, city_name: 'Sherbrooke', country_id: 2 },
  { id: 5, city_name: 'Saint- Jean de Terre - Neuve', country_id: 2 },
  { id: 6, city_name: 'Québec', country_id: 2 },
  { id: 7, city_name: 'Trois-Rivières', country_id: 2 },
  { id: 8, city_name: 'Rimouski', country_id: 2 },
  { id: 9, city_name: 'Abitibi-Témiscamingue', country_id: 2 },
  { id: 10, city_name: 'Outaouais', country_id: 2 },
  { id: 11, city_name: 'Toronto', country_id: 2 },
  { id: 12, city_name: 'Saguenay', country_id: 2 },
  { id: 13, city_name: 'Kaohsiung', country_id: 3 },
  { id: 14, city_name: 'Oklahoma city', country_id: 4 },
  { id: 15, city_name: 'Hong Kong', country_id: 0 },
  { id: 16, city_name: 'Tianjin', country_id: 0 },
  { id: 17, city_name: 'Tongji', country_id: 0 },
  { id: 18, city_name: 'Xi\'an', country_id: 0 },
  { id: 19, city_name: 'Incheon', country_id: 5 },
  { id: 20, city_name: 'Bangkok', country_id: 6 },
  { id: 21, city_name: 'Danang', country_id: 7 },
  { id: 22, city_name: 'Cottbus', country_id: 8 },
  { id: 23, city_name: 'Darmstadt', country_id: 8 },
  { id: 24, city_name: 'Brunswick', country_id: 8 },
  { id: 25, city_name: 'Bruxelles', country_id: 9 },
  { id: 26, city_name: 'Liège', country_id: 9 },
  { id: 27, city_name: 'Louvain', country_id: 9 },
  { id: 28, city_name: 'Mons', country_id: 9 },
  { id: 29, city_name: 'Aalborg', country_id: 10 },
  { id: 30, city_name: 'Copenhague', country_id: 10 },
  { id: 31, city_name: 'Catalogne', country_id: 11 },
  { id: 32, city_name: 'La Corogne ', country_id: 11 },
  { id: 33, city_name: 'Grenade', country_id: 11 },
  { id: 34, city_name: 'Las Palmas de Grande Canarie', country_id: 11 },
  { id: 35, city_name: 'Madrid', country_id: 11 },
  { id: 36, city_name: 'Séville', country_id: 11 },
  { id: 37, city_name: 'Budapest', country_id: 12 },
  { id: 38, city_name: 'Dublin', country_id: 13 },
  { id: 39, city_name: 'Bologne', country_id: 14 },
  { id: 40, city_name: 'Turin', country_id: 14 },
  { id: 41, city_name: 'Milan', country_id: 14 },
  { id: 42, city_name: 'Vérone', country_id: 14 },
  { id: 43, city_name: 'Aquila', country_id: 14 },
  { id: 44, city_name: 'Naples', country_id: 14 },
  { id: 45, city_name: 'Rome', country_id: 14 },
  { id: 46, city_name: 'Trente', country_id: 14 },
  { id: 47, city_name: 'Trondheim', country_id: 15 },
  { id: 48, city_name: 'Gdansk', country_id: 16 },
  { id: 49, city_name: 'Cracovie', country_id: 16 },
  { id: 50, city_name: 'Varsovie', country_id: 16 },
  { id: 51, city_name: 'Lisbonne', country_id: 17 },
  { id: 52, city_name: 'Porto', country_id: 17 },
  { id: 53, city_name: 'Sibiu', country_id: 18 },
  { id: 54, city_name: 'Timisoara', country_id: 18 },
  { id: 55, city_name: 'Bucarest', country_id: 18 },
  { id: 56, city_name: 'Newcastle upon Tyne', country_id: 19 },
  { id: 57, city_name: 'Linköping', country_id: 20 },
  { id: 58, city_name: 'Santa Fe', country_id: 21 },
  { id: 59, city_name: 'Fortaleza', country_id: 1 },
  { id: 60, city_name: 'Sobral', country_id: 1 },
  { id: 61, city_name: 'Barbalha', country_id: 1 },
  { id: 62, city_name: 'Vitória', country_id: 11 },
  { id: 63, city_name: 'Yaoundé', country_id: 22 },
  { id: 64, city_name: 'Bari', country_id: 14 },
  { id: 65, city_name: 'Rabat', country_id: 23 },
  { id: 66, city_name: 'Tétouan', country_id: 23 },
  { id: 67, city_name: 'Berne', country_id: 24 },
  { id: 68, city_name: 'Lomé', country_id: 25 }
]);
