const BaseModel = require('./base-model');

module.exports = new BaseModel('language', t => {
  t.integer('university_id').references('id').inTable('exchange_university');
  t.string('language', 20);
  t.enum('level', ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']);
  t.primary(['university_id', 'language']);
},
[
  { university_id: 0, language: 'Portuguais', level: 'B2' },
  { university_id: 1, language: 'Anglais', level: 'B2' },
  { university_id: 2, language: 'Anglais', level: 'B1' },
  { university_id: 3, language: 'Anglais', level: 'B2' },
  { university_id: 4, language: 'Anglais', level: 'B2' },
  { university_id: 5, language: 'Anglais', level: 'B2' },
  { university_id: 6, language: 'Français', level: 'B2' },
  { university_id: 7, language: 'Français', level: 'B2' },
  { university_id: 8, language: 'Français', level: 'B2' },
  { university_id: 9, language: 'Français', level: 'B2' },
  { university_id: 10, language: 'Anglais', level: 'B2' },
  { university_id: 11, language: 'Anglais', level: 'B2' },
  { university_id: 12, language: 'Anglais', level: 'B2' },
  { university_id: 13, language: 'Anglais', level: 'B1' },
  { university_id: 13, language: 'Français', level: 'B2' },
  { university_id: 14, language: 'Français', level: 'B2' },
  { university_id: 15, language: 'Anglais', level: 'B2' },
  { university_id: 16, language: 'Anglais', level: 'B2' },
  { university_id: 17, language: 'Chinois', level: 'B2' },
  { university_id: 17, language: 'Anglais', level: 'B1' },
  { university_id: 18, language: 'Anglais', level: 'B1' },
  { university_id: 19, language: 'Chinois', level: 'B1' },
  { university_id: 19, language: 'Anglais', level: 'B2' },
  { university_id: 20, language: 'Chinois', level: 'B1' },
  { university_id: 20, language: 'Anglais', level: 'B2' },
  { university_id: 21, language: 'Chinois', level: 'B1' },
  { university_id: 21, language: 'Anglais', level: 'B2' },
  { university_id: 22, language: 'Chinois', level: 'B1' },
  { university_id: 22, language: 'Anglais', level: 'B2' },
  { university_id: 23, language: 'Coréen', level: 'B1' },
  { university_id: 23, language: 'Anglais', level: 'B1' },
  { university_id: 24, language: 'Anglais', level: 'B1' },
  { university_id: 25, language: 'vietnamien', level: 'B1' },
  { university_id: 25, language: 'Anglais', level: 'B1' },
  { university_id: 26, language: 'Allemand', level: 'B1' },
  { university_id: 26, language: 'Anglais', level: 'B2' },
  { university_id: 27, language: 'Allemand', level: 'B1' },
  { university_id: 27, language: 'Anglais', level: 'B2' },
  { university_id: 28, language: 'Allemand', level: 'B1' },
  { university_id: 28, language: 'Anglais', level: 'B2' },
  { university_id: 29, language: 'Allemand', level: 'B1' },
  { university_id: 29, language: 'Anglais', level: 'B2' },
  { university_id: 30, language: 'Français', level: 'B1' },
  { university_id: 30, language: 'Anglais', level: 'B2' },
  { university_id: 31, language: 'Français', level: 'B1' },
  { university_id: 31, language: 'Anglais', level: 'B2' },
  { university_id: 32, language: 'Français', level: 'B1' },
  { university_id: 32, language: 'Anglais', level: 'B2' },
  { university_id: 33, language: 'Allemand', level: 'B1' },
  { university_id: 33, language: 'Anglais', level: 'B2' },
  { university_id: 34, language: 'Allemand', level: 'B1' },
  { university_id: 34, language: 'Anglais', level: 'B2' },
  { university_id: 35, language: 'Espagnol', level: 'B1' },
  { university_id: 35, language: 'Anglais', level: 'B1' },
  { university_id: 36, language: 'Espagnol', level: 'B1' },
  { university_id: 37, language: 'Espagnol', level: 'B1' },
  { university_id: 38, language: 'Espagnol', level: 'B1' },
  { university_id: 39, language: 'Espagnol', level: 'B1' },
  { university_id: 40, language: 'Anglais', level: 'B2' },
  { university_id: 41, language: 'Anglais', level: 'B2' },
  { university_id: 42, language: 'Anglais', level: 'B2' },
  { university_id: 43, language: 'Anglais', level: 'B2' },
  { university_id: 44, language: 'Anglais', level: 'B2' },
  { university_id: 45, language: 'Anglais', level: 'B2' },
  { university_id: 46, language: 'Anglais', level: 'B2' },
  { university_id: 47, language: 'Anglais', level: 'B2' },
  { university_id: 48, language: 'Anglais', level: 'B2' },
  { university_id: 49, language: 'Anglais', level: 'B2' },
  { university_id: 50, language: 'Anglais', level: 'B2' },
  { university_id: 51, language: 'Anglais', level: 'B2' },
  { university_id: 52, language: 'Anglais', level: 'B2' },
  { university_id: 53, language: 'Anglais', level: 'B2' },
  { university_id: 54, language: 'Anglais', level: 'B2' },
  { university_id: 55, language: 'Anglais', level: 'B2' },
  { university_id: 56, language: 'Anglais', level: 'B2' },
  { university_id: 57, language: 'Anglais', level: 'B2' },
  { university_id: 58, language: 'Anglais', level: 'B2' },
  { university_id: 59, language: 'Anglais', level: 'B2' },
  { university_id: 60, language: 'Anglais', level: 'B2' },
  { university_id: 61, language: 'Anglais', level: 'B2' },
  { university_id: 62, language: 'Italien', level: 'B1' },
  { university_id: 63, language: 'Italien', level: 'B1' },
  { university_id: 64, language: 'Anglais', level: 'B2' },
  { university_id: 65, language: 'Anglais', level: 'B2' },
  { university_id: 66, language: 'Anglais', level: 'B2' },
  { university_id: 67, language: 'Anglais', level: 'B2' },
  { university_id: 68, language: 'Anglais', level: 'B2' },
  { university_id: 69, language: 'Anglais', level: 'B2' }
]
);
