const BaseModel = require('./base-model');

module.exports = new BaseModel('university_language', t => {
  t.integer('university_id').references('id').inTable('exchange_university');
  t.integer('language_id', 20).references('id').inTable('language');
  t.enum('level', ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']);
  t.primary(['university_id', 'language_id']);
},
[
  { university_id: 0, language_id: 8, level: 'B2' },
  { university_id: 1, language_id: 0, level: 'B2' },
  { university_id: 2, language_id: 0, level: 'B1' },
  { university_id: 3, language_id: 0, level: 'B2' },
  { university_id: 4, language_id: 0, level: 'B2' },
  { university_id: 5, language_id: 0, level: 'B2' },
  { university_id: 6, language_id: 1, level: 'B2' },
  { university_id: 7, language_id: 1, level: 'B2' },
  { university_id: 8, language_id: 1, level: 'B2' },
  { university_id: 9, language_id: 1, level: 'B2' },
  { university_id: 10, language_id: 0, level: 'B2' },
  { university_id: 11, language_id: 0, level: 'B2' },
  { university_id: 12, language_id: 0, level: 'B2' },
  { university_id: 13, language_id: 0, level: 'B1' },
  { university_id: 13, language_id: 1, level: 'B2' },
  { university_id: 14, language_id: 1, level: 'B2' },
  { university_id: 15, language_id: 0, level: 'B2' },
  { university_id: 16, language_id: 0, level: 'B2' },
  { university_id: 17, language_id: 2, level: 'B2' },
  { university_id: 17, language_id: 0, level: 'B1' },
  { university_id: 18, language_id: 0, level: 'B1' },
  { university_id: 19, language_id: 2, level: 'B1' },
  { university_id: 19, language_id: 0, level: 'B2' },
  { university_id: 20, language_id: 2, level: 'B1' },
  { university_id: 20, language_id: 0, level: 'B2' },
  { university_id: 21, language_id: 2, level: 'B1' },
  { university_id: 21, language_id: 0, level: 'B2' },
  { university_id: 22, language_id: 2, level: 'B1' },
  { university_id: 22, language_id: 0, level: 'B2' },
  { university_id: 23, language_id: 4, level: 'B1' },
  { university_id: 23, language_id: 0, level: 'B1' },
  { university_id: 24, language_id: 0, level: 'B1' },
  { university_id: 25, language_id: 5, level: 'B1' },
  { university_id: 25, language_id: 0, level: 'B1' },
  { university_id: 26, language_id: 3, level: 'B1' },
  { university_id: 26, language_id: 0, level: 'B2' },
  { university_id: 27, language_id: 3, level: 'B1' },
  { university_id: 27, language_id: 0, level: 'B2' },
  { university_id: 28, language_id: 3, level: 'B1' },
  { university_id: 28, language_id: 0, level: 'B2' },
  { university_id: 29, language_id: 3, level: 'B1' },
  { university_id: 29, language_id: 0, level: 'B2' },
  { university_id: 30, language_id: 1, level: 'B1' },
  { university_id: 30, language_id: 0, level: 'B2' },
  { university_id: 31, language_id: 1, level: 'B1' },
  { university_id: 31, language_id: 0, level: 'B2' },
  { university_id: 32, language_id: 1, level: 'B1' },
  { university_id: 32, language_id: 0, level: 'B2' },
  { university_id: 33, language_id: 3, level: 'B1' },
  { university_id: 33, language_id: 0, level: 'B2' },
  { university_id: 34, language_id: 3, level: 'B1' },
  { university_id: 34, language_id: 0, level: 'B2' },
  { university_id: 35, language_id: 7, level: 'B1' },
  { university_id: 35, language_id: 0, level: 'B1' },
  { university_id: 36, language_id: 7, level: 'B1' },
  { university_id: 37, language_id: 7, level: 'B1' },
  { university_id: 38, language_id: 7, level: 'B1' },
  { university_id: 39, language_id: 7, level: 'B1' },
  { university_id: 40, language_id: 0, level: 'B2' },
  { university_id: 41, language_id: 0, level: 'B2' },
  { university_id: 42, language_id: 0, level: 'B2' },
  { university_id: 43, language_id: 0, level: 'B2' },
  { university_id: 44, language_id: 0, level: 'B2' },
  { university_id: 45, language_id: 0, level: 'B2' },
  { university_id: 46, language_id: 0, level: 'B2' },
  { university_id: 47, language_id: 0, level: 'B2' },
  { university_id: 48, language_id: 0, level: 'B2' },
  { university_id: 49, language_id: 0, level: 'B2' },
  { university_id: 50, language_id: 0, level: 'B2' },
  { university_id: 51, language_id: 0, level: 'B2' },
  { university_id: 52, language_id: 0, level: 'B2' },
  { university_id: 53, language_id: 0, level: 'B2' },
  { university_id: 54, language_id: 0, level: 'B2' },
  { university_id: 55, language_id: 0, level: 'B2' },
  { university_id: 56, language_id: 0, level: 'B2' },
  { university_id: 57, language_id: 0, level: 'B2' },
  { university_id: 58, language_id: 0, level: 'B2' },
  { university_id: 59, language_id: 0, level: 'B2' },
  { university_id: 60, language_id: 0, level: 'B2' },
  { university_id: 61, language_id: 0, level: 'B2' },
  { university_id: 62, language_id: 6, level: 'B1' },
  { university_id: 63, language_id: 6, level: 'B1' },
  { university_id: 64, language_id: 0, level: 'B2' },
  { university_id: 65, language_id: 0, level: 'B2' },
  { university_id: 66, language_id: 0, level: 'B2' },
  { university_id: 67, language_id: 0, level: 'B2' },
  { university_id: 68, language_id: 0, level: 'B2' },
  { university_id: 69, language_id: 0, level: 'B2' }
]
);
